### ISSUE TITLE
Trustless Bridge advance version - support EOS Native tokens tranfering from EOS to EVM 

### ISSUE THREAD

**Issue by Joshua2Mars** [eosnetworkfoundation/eos-evm#498]
1. Advance version of bridge to support EOS native tokens like USDT(EOS) tranfering from EOS to EVM
2. An integrate UI(Multichain, Trustless Bridge, other bridge) to transfer different kinds of tokens between EOS, EVM and other EVM compatible chains
```[tasklist]
### Tasks
- [ ] https://github.com/eosnetworkfoundation/eos-evm/issues/608
- [ ] https://github.com/eosnetworkfoundation/eos-evm/issues/609
- [ ] https://github.com/eosnetworkfoundation/eos-evm/issues/610
- [ ] https://github.com/eosnetworkfoundation/eos-evm/issues/611
- [ ] https://github.com/eosnetworkfoundation/evm-bridge-contracts/issues/1
- [ ] https://github.com/eosnetworkfoundation/eos-evm/issues/612
- [ ] https://github.com/eosnetworkfoundation/eos-evm/issues/613
```

**Comment by Joshua2Mars** [comment]
Need to create a ticket for spike
